### ISSUE TITLE
ERR_SOCKET_BAD_PORT

### ISSUE THREAD

**Issue by gersteba** [MorphixProductions/node-visca-over-ip#7]
Although sending a VISCA command with 'Packet Sender' application to the same port number succeeds, with this script I get an ERR_SOCKET_BAD_PORT error:
```
RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received undefined.
    at new NodeError (node:internal/errors:405:5)
    at validatePort (node:internal/validators:409:11)
    at Socket.send (node:dgram:632:12)
    at ViscaCamera.sendDirect ([PATH]\dist\Camera.js:98:21)
    at ViscaCamera.sendCommand ([PATH]\dist\Camera.js:132:18)
    at [PATH]\test.js:17:7
    at ViscaCamera.on ([PATH]\dist\Camera.js:80:13)
    at Object.<anonymous> ([PATH]\test.js:5:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) {
  code: 'ERR_SOCKET_BAD_PORT'
}
```

Why?

**Comment by giumarzo** [comment]
Add setTimeout 
 setTimeout(() => {
        camera.sendCommand(command);
 }, 1000);
